### ISSUE TITLE
El bot apunta a gente a la raid, pero no actualiza el mensaje para añadirlo.

### ISSUE THREAD

**Issue by tdguchi** [gentakojima/detectiveyellowcopyrightedrat#7]
Tengo instalado el bot en un VPS, con ubuntu 16.04, mysql 5.7 y python 3.5

está cargada la base de datos, y la conexión con esta funciona, ya que la tabla usuarios contiene a los usuarios, y la raid la guarda.

pero al clickar en voy, no suma, (tampoco si posteriormente se pincha en +1) 

el debug.log muestra lo siguiente:

2018-03-21 00:22:09,458 Connected to database from thread 139995108980480 
2018-03-21 00:22:09,458 storagemethods:getGroup: -1001144346583
2018-03-21 00:22:09,460 supportmethods:update_message: -1001144346583 7679 {'inline_keyboard': [[{'text': '🙋Voy', 'callback_data': 'voy'}, {'text': '🌕+1', 'callback_data': 'plus1yellow'}, {'text': '🔵+1', 'callback_data': 'plus1blue'}, {'text': '🔴+1', 'callback_data': 'plus1red'}], [{'text': '✅Estoy', 'callback_data': 'estoy'}, {'text': '🕒Tardo', 'callback_data': 'llegotarde'}, {'text': '🙅No voy', 'callback_data': 'novoy'}]]}
2018-03-21 00:22:09,460 Connected to database from thread 139995108980480 
2018-03-21 00:22:09,461 storagemethods:getRaidByMessage: -1001144346583 7679
2018-03-21 00:22:09,461 supportmethods:format_message: {'edited': 0, 'status': 'waiting', 'message': 7679, 'pokemon': 'Lugia', 'addedtime': datetime.datetime(2018, 3, 21, 0, 22), 'gimnasio_text': 'asdasdsa', 'refloated': 0, 'gimnasio_id': None, 'id': 116, 'egg': None, 'grupo_id': -1001144346583, 'usuario_id': 11016102, 'timeend': None, 'timeraid': datetime.datetime(2018, 3, 21, 18, 30)}
2018-03-21 00:22:09,462 Connected to database from thread 139995108980480 
2018-03-21 00:22:09,462 storagemethods:getCreadorRaid: 116
2018-03-21 00:22:09,464 Connected to database from thread 139995108980480 
2018-03-21 00:22:09,464 storagemethods:getGroup: -1001144346583
2018-03-21 00:22:09,466 Connected to database from thread 139995108980480 
2018-03-21 00:22:09,466 storagemethods:getRaidPeople: 116
2018-03-21 00:22:09,467 supportmethods:format_text_day 2018-03-21 18:30:00 Europe/Madrid
2018-03-21 00:22:09,467 supportmethods:extract_time 2018-03-21 18:30:00
2018-03-21 00:22:09,467 supportmethods::extract_time extracted 18:30
2018-03-21 00:22:09,468 Connected to database from thread 139995108980480 
2018-03-21 00:22:09,468 storagemethods:getGroupTimezoneOffsetFromServer: -1001144346583
2018-03-21 00:22:09,468 An uncaught error was raised while running the promise
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telegram/utils/promise.py", line 57, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "detectivepikachubot.py", line 1883, in raidbutton
    update_message(chat_id, message_id, reply_markup, bot)
  File "/root/pikachubot/supportmethods.py", line 172, in update_message
    text = format_message(raid)
  File "/root/pikachubot/supportmethods.py", line 267, in format_message
    diff_hours = getGroupTimezoneOffsetFromServer(group["id"])
  File "/root/pikachubot/storagemethods.py", line 210, in getGroupTimezoneOffsetFromServer
    localtz = get_localzone()
  File "/usr/local/lib/python3.5/dist-packages/tzlocal/unix.py", line 131, in get_localzone
    _cache_tz = _get_localzone()
  File "/usr/local/lib/python3.5/dist-packages/tzlocal/unix.py", line 70, in _get_localzone
    return pytz.timezone(etctz.replace(' ', '_'))
  File "/usr/local/lib/python3.5/dist-packages/pytz/__init__.py", line 180, in timezone
    raise UnknownTimeZoneError(zone)
pytz.exceptions.UnknownTimeZoneError: ''
2018-03-21 00:22:12,486 Ticking jobs with t=1521588132.486238
2018-03-21 00:22:12,486 Peeked at callback_remove_incomplete_raids with t=1521588132.486075
2018-03-21 00:22:12,486 Running job callback_remove_incomplete_raids
2018-03-21 00:22:12,486 supportmethods:remove_incomplete_raids
2018-03-21 00:22:12,486 Putting job callback_remove_incomplete_raids with t=1521588147.486075
2018-03-21 00:22:12,487 Peeked at callback_update_raids_status with t=1521588147.485510
2018-03-21 00:22:12,487 Next task isn't due yet. Finished!
2018-03-21 00:22:12,488 Connected to database from thread 139994660337408 
2018-03-21 00:22:12,488 storagemethods:removeIncompleteRaids
2018-03-21 00:22:16,339 Closing bot!

**Comment by gentakojima** [comment]
Prueba esto, abriendo una consola de python:

```
from tzlocal import get_localzone
tz = get_localzone()
tz
```

¿Funciona? ¿Qué te dice?

**Comment by tdguchi** [comment]
root@vps527338:~# python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from tzlocal import get_localzone
>>> tz = get_localzone()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/tzlocal/unix.py", line 131, in get_localzone
    _cache_tz = _get_localzone()
  File "/usr/local/lib/python3.5/dist-packages/tzlocal/unix.py", line 70, in _get_localzone
    return pytz.timezone(etctz.replace(' ', '_'))
  File "/usr/local/lib/python3.5/dist-packages/pytz/__init__.py", line 180, in timezone
    raise UnknownTimeZoneError(zone)
pytz.exceptions.UnknownTimeZoneError: ''
>>> tz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'tz' is not defined
>>> 

Da el mismo error que con el bot xD

**Comment by gentakojima** [comment]
Ok, pues reducimos el problema a eso. Supongo que algo en el entorno tendrás que te establece la zona horaria a nada.

Dime la salida de:

```
env
```

Seguramente sea la variable `TZ`. Si existe, bórrala:

```
unset TZ
```

O bien pon un timezone correcto, lo que mejor te parezca.

Si no es eso, a lo mejor con la salida de `env` vemos algo más.

**Comment by tdguchi** [comment]
```
root@vps527338:~# env
XDG_SESSION_ID=29
TERM=xterm-256color
SHELL=/bin/bash
SSH_CLIENT=XXXXXXXXXXXXX
SSH_TTY=/dev/pts/1
USER=root
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
MAIL=/var/mail/root
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
PWD=/root
LANG=en_US.UTF-8
SHLVL=1
HOME=/root
LOGNAME=root
XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
SSH_CONNECTION=XXXXXXXXXXXXXXXXX
LESSOPEN=| /usr/bin/lesspipe %s
XDG_RUNTIME_DIR=/run/user/0
LESSCLOSE=/usr/bin/lesspipe %s %s
_=/usr/bin/env
```


Esta es la salida del comando env

**Comment by ontherunvaro** [comment]
Hola, también puede ser útil la salida de `timedatectl`.

**Comment by tdguchi** [comment]
`root@vps527338:~# timedatectl
      Local time: Wed 2018-03-21 14:22:37 CET
  Universal time: Wed 2018-03-21 13:22:37 UTC
        RTC time: Wed 2018-03-21 13:22:37
       Time zone: Europe/Madrid (CET, +0100)
 Network time on: yes
NTP synchronized: yes
 RTC in local TZ: no
root@vps527338:~# 
`

**Comment by tdguchi** [comment]
He tocado tantas cosas que no sé que es lo que lo arregló, pero, https://unix.stackexchange.com/questions/110522/timezone-setting-in-linux

Simplemente hacer un sudo dpkg-reconfigure tzdata y el bot arranca crea raids, y apunta sin problema.

Ya comentaré si es definitivo xD

**Comment by gentakojima** [comment]
Así sea, me arreglo que se haya solucionado. Gracias @ontherunvaro por la sugerencia, no lo conocía.
